import { Question } from './types';

export const questions: Question[] = [
  {
    id: 1,
    text: 'Where is the Eiffel Tower?',
    lat: 48.8584,
    lng: 2.2945,
    hint: 'Famous Paris landmark',
    category: 'landmark',
  },
  {
    id: 2,
    text: 'Where is the Statue of Liberty?',
    lat: 40.6892,
    lng: -74.0445,
    hint: 'New York harbor',
    category: 'landmark',
  },
  {
    id: 3,
    text: 'Where is the Colosseum?',
    lat: 41.8902,
    lng: 12.4922,
    hint: 'Ancient Roman arena',
    category: 'landmark',
  },
  {
    id: 4,
    text: 'Where is the Great Wall at Badaling?',
    lat: 40.3652,
    lng: 116.0204,
    hint: 'North of Beijing',
    category: 'landmark',
  },
  {
    id: 5,
    text: 'Where is Machu Picchu?',
    lat: -13.1631,
    lng: -72.5450,
    hint: 'Inca citadel',
    category: 'landmark',
  },
  {
    id: 6,
    text: 'Where is Sydney Opera House?',
    lat: -33.8568,
    lng: 151.2153,
    hint: 'Australian landmark on the harbor',
    category: 'landmark',
  },
  {
    id: 7,
    text: 'Where is the Taj Mahal?',
    lat: 27.1751,
    lng: 78.0421,
    hint: 'Indian mausoleum',
    category: 'landmark',
  },
  {
    id: 8,
    text: 'Where is Christ the Redeemer?',
    lat: -22.9519,
    lng: -43.2105,
    hint: 'Overlooking Rio de Janeiro',
    category: 'landmark',
  },
  {
    id: 9,
    text: 'Where is the Pyramids of Giza?',
    lat: 29.9792,
    lng: 31.1342,
    hint: 'Ancient Egyptian tombs',
    category: 'landmark',
  },
  {
    id: 10,
    text: 'Where is the Golden Gate Bridge?',
    lat: 37.8199,
    lng: -122.4783,
    hint: 'San Francisco iconic bridge',
    category: 'landmark',
  },
];
